const statusSelect=document.getElementById('status'), riskSelect=document.getElementById('risk'), confidenceInput=document.getElementById('confidence'), areaInput=document.getElementById('area');
const map=L.map('map').setView([23.29,82.12],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{y}/{x}.png'.replace('{y}/{x}','{x}/{y}'),{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);let markers=L.layerGroup().addTo(map),trendChart,legalChart;
const colour=x=>x.risk_level==='HIGH'?'#ef3b31':x.risk_level==='MEDIUM'?'#ff8619':x.status.startsWith('LEGAL')?'#3ebc69':'#f4c33f';
async function get(url){return (await fetch(url)).json()}function qp(){return `?status=${statusSelect.value}&risk=${riskSelect.value}&min_confidence=${confidenceInput.value/100}&min_area=${areaInput.value}`}
function kpi(label,value,cls=''){return `<div class="kpi ${cls}"><small>${label}</small><b>${value}</b></div>`}
async function init(){const s=await get('/api/summary');alertBadge.textContent=s.high;kpis.innerHTML=kpi('Monitored area',s.monitored_area_km2+' km²','blueK')+kpi('Mining sites',s.total)+kpi('High-risk sites',s.high,'redK')+kpi('Legal sites',s.legal,'greenK')+kpi('Suspicious sites',s.suspicious,'redK')+kpi('Estimated area',s.area+' ha','blueK');riskScore.textContent=s.risk_score+'/100';riskBars.innerHTML=`<div class="bar"><span>HIGH risk</span><i>${s.high}</i></div><div class="bar"><span>MEDIUM risk</span><i>${42-s.high-11}</i></div><div class="bar"><span>LOW risk</span><i>11</i></div>`;alerts.innerHTML=`<div class="alert"><b>▲ Demo alert</b><br>High-confidence change near protected area</div><div class="alert"><b>▲ Demo alert</b><br>Activity outside a permit boundary</div><div class="alert"><b>▲ Demo alert</b><br>Rapid surface-change pattern detected</div>`;let b=await get('/api/boundaries');L.geoJSON(b,{style:f=>({color:f.properties.kind==='permit'?'#3ebc69':f.properties.kind==='protected'?'#c7e540':'#bb68d8',weight:2,fillOpacity:.05})}).addTo(map);load();}
async function load(){const d=(await get('/api/detections'+qp())).items;markers.clearLayers();d.forEach(x=>L.circleMarker([x.latitude,x.longitude],{radius:7,color:'#fff',weight:1,fillColor:colour(x),fillOpacity:.95}).bindPopup(`<b>${x.id}</b><br>${x.status}<br>Risk ${x.risk}/100 · ${Math.round(x.probability*100)}% confidence`).addTo(markers));rows.innerHTML=d.slice(0,10).map(x=>`<tr onclick="showDetail('${x.id}')"><td>${x.id}</td><td>${x.date.slice(5)}</td><td>${x.latitude}, ${x.longitude}</td><td>${x.area_ha}</td><td>${Math.round(x.probability*100)}%</td><td><span class="pill ${x.status.startsWith('LEGAL')?'legal':''}">${x.status.replace('ILLEGAL — ','')}</span></td><td><span class="riskpill ${x.risk_level}">${x.risk}</span></td></tr>`).join('');drawCharts(d)}
function drawCharts(d){let dates={};d.forEach(x=>dates[x.date]=(dates[x.date]||0)+1);let labs=Object.keys(dates).sort();if(trendChart)trendChart.destroy();trendChart=new Chart(trend,{type:'line',data:{labels:labs,datasets:[{data:labs.map(x=>dates[x]),borderColor:'#75cb42',backgroundColor:'#75cb4230',fill:true,tension:.35}]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#9bb0b7',maxTicksLimit:4},grid:{display:false}},y:{ticks:{color:'#9bb0b7'},grid:{color:'#21343a'}}}}});let legal=d.filter(x=>x.status.startsWith('LEGAL')).length;if(legalChart)legalChart.destroy();legalChart=new Chart(legality,{type:'doughnut',data:{labels:['Suspicious','Legal'],datasets:[{data:[d.length-legal,legal],backgroundColor:['#ef573e','#49ba69']}]},options:{plugins:{legend:{labels:{color:'#d8e2e4',font:{size:10}}}}}})}
async function showDetail(id){let x=await get('/api/detections/'+id);detailContent.innerHTML=`<h2>${x.id}</h2><p class="detailStatus">${x.status} · ${x.risk_level} RISK (${x.risk}/100)</p><p><b>Location:</b> ${x.latitude}, ${x.longitude}<br><b>Satellite source:</b> ${x.source}<br><b>Mining probability:</b> ${Math.round(x.probability*100)}%<br><b>Estimated area:</b> ${x.area_ha} ha<br><b>Surface change:</b> ${x.change_db} dB</p><p>${x.explanation}</p><p><b>Recommendation:</b> Field verification required.</p>`;detail.showModal()}window.showDetail=showDetail;
confidenceInput.oninput=()=>confOut.textContent=confidenceInput.value+'%';areaInput.oninput=()=>areaOut.textContent=areaInput.value;apply.onclick=load;kml.onclick=()=>location.href='/api/export/kml';gpx.onclick=()=>location.href='/api/export/gpx';report.onclick=()=>location.href='/api/report';init();
